#include<stdio.h>
int main()
{
    int n,arr[100],i,j,k=0,c=0;
    float avg=0,sum=0;
    scanf("%d",&n);
    for(i=0;i<n;i++)
    {
        scanf("%d",&arr[i]);
    }
    for(i=0;i<n;i++)
    {
        c=0;
        for(j=0;j<n;j++)
        {
            if(arr[i]==arr[j])
            {
                c++;
                if(i!=j)
                {
                    arr[j]=0;
                }
            }
        }
        if(arr[i]==c)
        {
            sum+=arr[i];
            k++;
        }
    }
    if(k==0)
    {
        printf("-1");
    }
    else
    {
        printf("%.2f",sum/k);
    }
}
